using LinqToTwitter;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
namespace CCF2.Models
{
    public class UserTweetsViewModel
    {
        //Label with the twitter account name
        public string Label { get; set; }

        //List of tweets
        public ObservableCollection<TweetModel> Tweets { get; set; }

        //Authorisation keys and tokens to retrieve tweets
        private const string consumerKey = "9BrcbtKxlq5MOOlD44YAw";
        private const string consumerSecret = "rcLkRuQ0C91q55sp3qRbLAirzZ0zCPEiTCm2dvduPE";
        private const string twitterAccessToken = "1977695389-hif7PDMoTrJED8Nk0fbJ2eAAkdl9GgcPptLghwp";
        private const string twitterAccessTokenSecret = "R8MMzh5aFW7g3OWHeD9Tg8wEAGBWQWXKME0sAfIk";

        public UserTweetsViewModel()
        { }

        //Constructor that consutrcts a new model and retrieves all the tweets
        public UserTweetsViewModel(string userName, int count)
        {
            
            GetTwitterUserTimeLine(userName, count);
            
        }

        //Method is responsible for comminucating with the Twitter REST v1.1 API and gather tweets
        private void GetTwitterUserTimeLine(string userName, int count)
        {
            try
            {
                ObservableCollection<TweetModel> result = new ObservableCollection<TweetModel>();

                //Packaging Authentication details
                var auth = new SingleUserAuthorizer
                {
                    Credentials = new SingleUserInMemoryCredentials
                    {
                        ConsumerKey = consumerKey,
                        ConsumerSecret = consumerSecret,
                        TwitterAccessToken = twitterAccessToken,
                        TwitterAccessTokenSecret = twitterAccessTokenSecret
                    }
                };

                auth.Authorize();

                //Creating a session
                TwitterContext twitterCtx = new TwitterContext(auth);

                //Retreiving tweets
                var tweets = twitterCtx.Status.Where(tweet => tweet.ScreenName == userName && tweet.Type == StatusType.User).Take(count).ToList();
                
                //Loading tweets into the tweet model.
                foreach (var item in tweets)
                {
                    TweetModel tweet = new TweetModel()
                    {
                        Text = item.Text,

                        ScreenName = item.User.Name,
                        UserName = "@" + item.ScreenName,
                        PublicationDate = GetElapsedPeriod(item.CreatedAt),
                        Image = item.User.ProfileImageUrl

                    };
                    result.Add(tweet);

                }

                //Writing all the tweets into an XML file for offline use.
                XmlWriterSettings settings = new XmlWriterSettings();
                settings.Indent = true;
                using (XmlWriter writer = XmlWriter.Create(@"Resources/xml/Tweets.xml", settings))
                {
                    writer.WriteStartDocument();

                    writer.WriteComment("This file is generated by the program.");
                    writer.WriteStartElement("Tweets");
                    foreach (var item in tweets)
                    {
                        writer.WriteStartElement("Tweet");
                        writer.WriteAttributeString("Text", item.Text);
                        writer.WriteAttributeString("ScreenName", item.User.Name);
                        writer.WriteAttributeString("UserName", "@" + item.ScreenName);
                        writer.WriteAttributeString("PublicationDate", GetElapsedPeriod(item.CreatedAt));
                        writer.WriteAttributeString("Image", item.User.ProfileImageUrl);
                        writer.WriteEndElement();
                    }
                    writer.WriteEndElement();
                    writer.WriteEndDocument();
                    writer.Flush();
                    writer.Close();
                }
            }
            catch(LinqToTwitter.TwitterQueryException e)
            {

            }
            //return result;
        }

        /// <summary> 
        /// Get elapsed period from a date. 
        /// </summary> 
        /// <param name="d">Date</param> 
        /// <returns>Well formated elapsed period</returns> 
        /// <seealso cref="http://www.dotnetperls.com/pretty-date"/> 
        private string GetElapsedPeriod(DateTime d)
        {
            // 1. 
            // Get time span elapsed since the date. 
            TimeSpan s = DateTime.Now.Subtract(d);

            // 2. 
            // Get total number of days elapsed. 
            int dayDiff = (int)s.TotalDays;

            // 3. 
            // Get total number of seconds elapsed. 
            int secDiff = (int)s.TotalSeconds;

            // 5. 
            // Handle same-day times. 
            if (dayDiff == 0)
            {
                // A. 
                // Less than one minute ago. 
                if (secDiff < 60)
                {
                    return "just now";
                }
                // B. 
                // Less than 2 minutes ago. 
                if (secDiff < 120)
                {
                    return "1 minute ago";
                }
                // C. 
                // Less than one hour ago. 
                if (secDiff < 3600)
                {
                    return string.Format("{0} minutes ago",
                        Math.Floor((double)secDiff / 60));
                }
                // D. 
                // Less than 2 hours ago. 
                if (secDiff < 7200)
                {
                    return "1 hour ago";
                }
                // E. 
                // Less than one day ago. 
                if (secDiff < 86400)
                {
                    return string.Format("{0} hours ago",
                        Math.Floor((double)secDiff / 3600));
                }
            }
            // 6. 
            // Handle previous days. 
            if (dayDiff == 1)
            {
                return "yesterday";
            }
            if (dayDiff < 7)
            {
                return string.Format("{0} days ago",
                dayDiff);
            }
            if (dayDiff < 31)
            {
                return string.Format("{0} weeks ago",
                Math.Ceiling((double)dayDiff / 7));
            }


            return d.ToString();
        }
    }
} 


